src/objects/Log__c.object
<CustomObject>
    <description>This object will be used to store a log of any apex transactions</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <label>Messages</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/tests/test-factories/classes/SObjectTestFactory.cls
/**
 * @author Gavin Palmer (gavinhughpalmer@gmail.com)
 * @description This factory class is to be utilised within the tests of this package,
 *   the actual object it is creating is not important it is just when some kind of DML
 *   is needed in the test, as you can see below we have chosen to use the log object as
 *   this has no dependancies and has a low risk of failure to insert when being created.
 *
 * @date 2018-10-23
 **/
public with sharing class SObjectTestFactory extends AbstractSObjectTestFactory {
    public override SObject getSObject() {
        return new Log__c(
            Level__c = 'Information',
            Messages__c = 'Not a real log',
            Record_Id__c = null,
            Type__c = 'Fake'
        );
    }
}