src/objects/Log__c.object
<CustomObject>
    <description>This object will be used to store a log of any apex transactions</description>
    <fields>
        <fullName>Messages__c</fullName>
        <label>Messages</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/tests/utilities/logging/classes/LoggedQueueableTest.cls
/**
 * @author Gavin Palmer (gavinhughpalmer@gmail.com)
 * @version 1.0
 * @description Test class for the LoggedQueueable class
 *
 * 2019-02-06 : Gavin Palmer - Original
 **/
@IsTest(isParallel=true)
private class LoggedQueueableTest {
    private static final String LOG_MESSAGE = 'My test message';

    private class TestLog extends LoggedQueueable {
        protected override void execute() {
            log.error(LOG_MESSAGE);
        }
    }

    @IsTest
    private static void runTestLogWritten() {
        LoggedQueueable testQueueable = new TestLog();
        Test.startTest();
        testQueueable.enqueue();
        Test.stopTest();
        List<Log__c> logs = [SELECT Messages__c FROM Log__c];
        System.assertEquals(
            1,
            logs.size(),
            'A message should have been written when the queueable is ran'
        );
        Assert.contains(logs[0].Messages__c, LOG_MESSAGE);
    }
}