src/objects/Log__c.object
<CustomObject>
    <description>This object will be used to store a log of any apex transactions</description>
    <fields>
        <fullName>Level__c</fullName>
        <label>Level</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Error</fullName>
                </value>
                <value>
                    <fullName>Warning</fullName>
                </value>
                <value>
                    <fullName>Information</fullName>
                </value>
                <value>
                    <fullName>Debug</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Messages__c</fullName>
        <label>Messages</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Integration</fullName>
                </value>
                <value>
                    <fullName>Trigger</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Log</label>
    <nameField>
        <label>Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/utilities/logging/objects/Log_Event__e/Log_Event__e.object-meta.xml
<CustomObject>
    <label>Log Event</label>
    <pluralLabel>Log Events</pluralLabel>
</CustomObject>

force-app/main/utilities/logging/objects/Log_Event__e/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <description>This field determines the level of the log</description>
    <label>Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Log_Event__e/fields/Messages__c.field-meta.xml
<CustomField>
    <fullName>Messages__c</fullName>
    <label>Messages</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/utilities/logging/objects/Log_Event__e/fields/Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Record_Id__c</fullName>
    <description>This field will contain a reference to the record that the log is associated to</description>
    <externalId>true</externalId>
    <label>Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/utilities/logging/objects/Log_Event__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>This field is used to easily identify where the log has come from, it is a picklist to make filtering in list views/reports easier</description>
    <label>Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/tests/utilities/logging/classes/LogWriterTest.cls
/**
 * @author Gavin Palmer
 * @date 2019-04-20
 *
 **/
@IsTest(isParallel=true)
private class LogWriterTest {
    @IsTest
    private static void testAction() {
        Log_Event__e logEvent = new Log_Event__e(
            Level__c = 'Error',
            Messages__c = 'test2',
            Record_Id__c = 'test3',
            Type__c = 'test4'
        );

        Triggerable triggerAction = new LogWriter();
        triggerAction.register(new SObjectTriggerWrapper(logEvent, logEvent));
        triggerAction.performAction();
        List<Log__c> createdLogs = [
            SELECT Level__c, Messages__c, Record_Id__c, Type__c
            FROM Log__c
        ];

        Assert.areEqual(
            1,
            createdLogs.size(),
            'A single log should have been created during the conversion process'
        );
        Assert.areEqual(
            logEvent.Level__c,
            createdLogs[0].Level__c,
            'The level field has not been converted correctly'
        );
        Assert.areEqual(
            logEvent.Messages__c,
            createdLogs[0].Messages__c,
            'The messages field has not been converted correctly'
        );
        Assert.areEqual(
            logEvent.Record_Id__c,
            createdLogs[0].Record_Id__c,
            'The record id field has not been converted correctly'
        );
        Assert.areEqual(
            logEvent.Type__c,
            createdLogs[0].Type__c,
            'The type field has not been converted correctly'
        );
    }
}