force-app/main/utilities/configuration-management/objects/Configuration__c/Configuration__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This custom setting will be used to control the automation / validation in the system</description>
    <label>Configuration</label>
</CustomObject>

force-app/main/utilities/configuration-management/objects/Configuration__c/fields/Are_Processes_Off__c.field-meta.xml
<CustomField>
    <fullName>Are_Processes_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox determines if the process builders in the system are turned off</description>
    <label>Are Processes Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/utilities/configuration-management/objects/Configuration__c/fields/Are_Triggers_Off__c.field-meta.xml
<CustomField>
    <fullName>Are_Triggers_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field will be used to turn off the apex triggers in the system</description>
    <label>Are Triggers Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/utilities/configuration-management/objects/Configuration__c/fields/Are_Validations_Off__c.field-meta.xml
<CustomField>
    <fullName>Are_Validations_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will be used to turn off validation rules to allow saves of any records</description>
    <label>Are Validations Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/utilities/objects/Configuration__c/fields/Are_Workflows_Off__c.field-meta.xml
<CustomField>
    <fullName>Are_Workflows_Off__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This setting will be used to turn off the workflow rules that are configured in the system</description>
    <label>Are Workflows Off</label>
    <type>Checkbox</type>
</CustomField>

force-app/tests/utilities/configuration-management/classes/ConfigurationManagerTest.cls
/**
 * @author Gavin Palmer
 * @date 2018-06-27
 *
 **/
@IsTest(isParallel=true)
private class ConfigurationManagerTest {
    @IsTest
    private static void singletonTest() {
        ConfigurationManager initialInstance = ConfigurationManager.getInstance();
        ConfigurationManager secondaryInstance = ConfigurationManager.getInstance();
        // We have to use a comparison to validate the exact instance is the same
        Assert.isTrue(
            initialInstance === secondaryInstance,
            'The get instance method should always return the same instance of the ConfigurationManager'
        );
    }

    @IsTest
    private static void turnAutomationsOnTest() {
        ConfigurationManager.turnAutomationsOn();

        Configuration__c configurationSetting = Configuration__c.getInstance();
        Assert.isFalse(
            configurationSetting.Are_Triggers_Off__c,
            'The trigger should all be turned on'
        );
        Assert.isFalse(
            configurationSetting.Are_Workflows_Off__c,
            'The workflows should all be turned on'
        );
        Assert.isFalse(
            configurationSetting.Are_Validations_Off__c,
            'The validations should all be turned on'
        );
        Assert.isFalse(
            configurationSetting.Are_Processes_Off__c,
            'The processes should all be turned on'
        );
    }

    @IsTest
    private static void turnAutomationsOffTest() {
        ConfigurationManager.turnAutomationsOff();

        Configuration__c configurationSetting = Configuration__c.getInstance();
        Assert.isTrue(
            configurationSetting.Are_Triggers_Off__c,
            'The triggers should all be turned on'
        );
        Assert.isTrue(
            configurationSetting.Are_Workflows_Off__c,
            'The workflows should all be turned on'
        );
        Assert.isTrue(
            configurationSetting.Are_Validations_Off__c,
            'The validations should all be turned on'
        );
        Assert.isTrue(
            configurationSetting.Are_Processes_Off__c,
            'The processes should all be turned on'
        );
    }

    @IsTest
    private static void areTriggersOffTestNoSetting() {
        Assert.isTrue(
            ConfigurationManager.getInstance().areTriggersOn(),
            'The triggers should always be off by default, ie when a configuration record does not exist in the system'
        );
    }

    @IsTest
    private static void toggleTriggersTest() {
        ConfigurationManager configuration = ConfigurationManager.getInstance();
        configuration.turnTriggersOff();
        Assert.isTrue(
            configuration.areTriggersOff(),
            'Triggers should have truned off after the off method is called'
        );
        configuration.turnTriggersOn();
        Assert.isTrue(
            configuration.areTriggersOn(),
            'Triggers should have truned On after the On method is called'
        );
    }

    @IsTest
    private static void commitChangesTestWithoutExistingSetting() {
        Assert.areEqual(
            0,
            [SELECT COUNT() FROM Configuration__c],
            'There should be no Configuration__c records in the system before the save method is called'
        );
        ConfigurationManager configuration = ConfigurationManager.getInstance();
        configuration.commitChanges();
        Assert.areEqual(
            1,
            [SELECT COUNT() FROM Configuration__c],
            'There should be 1 Configuration__c records after the bypass method is called'
        );
    }

    @IsTest
    private static void commitChangesTestWithExistingSettingWorkflows() {
        Configuration__c configurationSetting = new Configuration__c(
            Are_Workflows_Off__c = true,
            SetupOwnerId = UserInfo.getUserId()
        );
        insert configurationSetting;
        ConfigurationManager configuration = ConfigurationManager.getInstance();
        configuration.turnWorkflowsOn();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Workflows_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isFalse(
            configurationSetting.Are_Workflows_Off__c,
            'The Configuration__c setting should have been comitted with workflows on'
        );
        configuration.turnWorkflowsOff();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Workflows_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isTrue(
            configurationSetting.Are_Workflows_Off__c,
            'The Configuration__c setting should have been comitted with workflows off'
        );
    }

    @IsTest
    private static void commitChangesTestWithExistingSettingValidations() {
        Configuration__c configurationSetting = new Configuration__c(
            Are_Validations_Off__c = true,
            SetupOwnerId = UserInfo.getUserId()
        );
        insert configurationSetting;
        ConfigurationManager configuration = ConfigurationManager.getInstance();
        configuration.turnValidationsOn();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Validations_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isFalse(
            configurationSetting.Are_Validations_Off__c,
            'The Configuration__c setting should have been comitted with Validations on'
        );
        configuration.turnValidationsOff();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Validations_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isTrue(
            configurationSetting.Are_Validations_Off__c,
            'The Configuration__c setting should have been comitted with Validations off'
        );
    }

    @IsTest
    private static void commitChangesTestWithExistingSettingProcesses() {
        Configuration__c configurationSetting = new Configuration__c(
            Are_Processes_Off__c = true,
            SetupOwnerId = UserInfo.getUserId()
        );
        insert configurationSetting;
        ConfigurationManager configuration = ConfigurationManager.getInstance();
        configuration.turnProcessesOn();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Processes_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isFalse(
            configurationSetting.Are_Processes_Off__c,
            'The Configuration__c setting should have been comitted with Processes on'
        );
        configuration.turnProcessesOff();
        configuration.commitChanges();

        configurationSetting = [
            SELECT Are_Processes_Off__c
            FROM Configuration__c
            WHERE Id = :configurationSetting.Id
        ];
        Assert.isTrue(
            configurationSetting.Are_Processes_Off__c,
            'The Configuration__c setting should have been comitted with Processes off'
        );
    }
}