force-app/main/utilities/logging/profiler/objects/Apex_Profiling_Warning_Limit__mdt/Apex_Profiling_Warning_Limit__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type will be used in the profiling of the apex code by the logging framework, the name of the record should be provided as the limit type that should be used. The format will be based on the methods from the Limits class (eg. for the Limits.getQueries, you should name the record Queries).
The default limit will be 75%.</description>
    <label>Apex Profiling Warning Limit</label>
    <pluralLabel>Apex Profiling Warning Limits</pluralLabel>
</CustomObject>

force-app/main/utilities/logging/profiler/objects/Apex_Profiling_Warning_Limit__mdt/fields/Ignore_Limit__c.field-meta.xml
<CustomField>
    <fullName>Ignore_Limit__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will control if the limit should be ignored when running the profiling, ie this could be useful if a limit is always likely to be hit</description>
    <label>Ignore Limit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/utilities/logging/profiler/objects/Apex_Profiling_Warning_Limit__mdt/fields/Warning_Level__c.field-meta.xml
<CustomField>
    <fullName>Warning_Level__c</fullName>
    <description>If the number of the specified level hits this volume against the total limit a warning log message will be written into the logging framework</description>
    <label>Warning Level</label>
    <precision>4</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

force-app/main/utilities/logging/profiler/classes/Profiler.cls
/**
 * @author Gavin Palmer
 * @date 2020-10-08
 * @group Logging
 * @description This is a generic profiling class, which allows implementations to report on certain limits within the environment.
 *
 **/
public abstract without sharing class Profiler {
    @testVisible
    private static final Decimal DEFAULT_WARNING_PERCENTAGE = 0.75;
    @testVisible
    private final Map<String, ProfileInfo> profilingInfos = new Map<String, ProfileInfo>();
    private Boolean isBreachingWarning = false;
    private static final Map<String, Decimal> WARNING_PERCENTAGES = new Map<String, Decimal>();
    private static final Set<String> IGNORE_LIMITS = new Set<String>();

    static {
        for (Apex_Profiling_Warning_Limit__mdt warningLimit : [
            SELECT DeveloperName, Ignore_Limit__c, Warning_Level__c
            FROM Apex_Profiling_Warning_Limit__mdt
        ]) {
            if (warningLimit.Ignore_Limit__c) {
                IGNORE_LIMITS.add(warningLimit.DeveloperName);
            } else {
                WARNING_PERCENTAGES.put(warningLimit.DeveloperName, warningLimit.Warning_Level__c);
            }
        }
    }

    public Profiler() {
        refreshProfiling();
    }

    public Boolean isBreachingWarning() {
        return isBreachingWarning;
    }

    /**
     * @description This method should be implemented in the base classes to refresh the profiling limits,
     * this will be called from the constructor and then at any point before this is planned to execute
     *
     **/
    public abstract void refreshProfiling();

    protected void addProfilingInfo(String limitName, Integer recorded, Integer limitTotal) {
        if (!IGNORE_LIMITS.contains(limitName)) {
            ProfileInfo profilingInfo = new ProfileInfo(limitName, recorded, limitTotal);
            isBreachingWarning = isBreachingWarning || profilingInfo.isBreachingWarning();
            profilingInfos.put(profilingInfo.limitName, profilingInfo);
        }
    }

    /**
     * @description This method is used to generate the report, each line that is breeching the warning will be marked as Warning
     *
     **/
    public String generateProfilingReport() {
        StringBuilder report = new StringBuilder();
        report.setSeparator('\n');
        for (ProfileInfo profile : profilingInfos.values()) {
            report.append(profile.getReportLine());
        }
        return report.toString();
    }

    private class ProfileInfo {
        private final String limitName;
        @testVisible
        private final Integer recorded;
        @testVisible
        private final Integer limitTotal;

        private ProfileInfo(String limitName, Integer recorded, Integer limitTotal) {
            this.limitName = limitName;
            this.recorded = recorded;
            this.limitTotal = limitTotal;
        }

        private Decimal getPercentage() {
            return limitTotal == 0
                ? 0
                : 1 - Decimal.valueOf(limitTotal - recorded) / Decimal.valueOf(limitTotal);
        }

        private String getReportLine() {
            String prefix = isBreachingWarning() ? 'Warning hit for ' : 'Number of ';
            return prefix + limitName + ': ' + recorded + ' of ' + limitTotal;
        }

        private Boolean isBreachingWarning() {
            Decimal warningPercentage = WARNING_PERCENTAGES.containsKey(limitName)
                ? (WARNING_PERCENTAGES.get(limitName) / 100)
                : DEFAULT_WARNING_PERCENTAGE;
            return getPercentage() > warningPercentage;
        }
    }
}